### ISSUE TITLE
[FEATURE] Route for current documentation (https://cadence-lang.org/docs)

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence-lang.org#14]
### Issue to be solved

There is currently no way to go / link to the current documentation without knowing the version number.

For example, the current documentation is at https://cadence-lang.org/docs/0.42, but that will change in the future

### Suggest A Solution

Add a route for https://cadence-lang.org/docs, which redirects to the current documentation, e.g. https://cadence-lang.org/docs/0.42.

This redirect should also work for sub-pages.

This feature exists on developers.flow.com. For example, https://developers.flow.com/cadence/language/syntax is the documentation for the Syntax of Cadence in the current version.

**Comment by bthaile** [comment]
could add a redirect `current` would look like this `cadence-lang.org/docs/current` that will redirect to the newest version. would have to update the redirect when a new version is published.

**Comment by turbolent** [comment]
`/docs/current` would be fine, but we'll probably don't want to have to manually update it, as that will just be forgotten. Is there any way to automate it? How does it work on developers.flow.com?
