### ISSUE TITLE
[BUG] Edit this page links are broken

### ISSUE THREAD

**Issue by alilloig** [onflow/cadence-lang.org#24]
### Current Behavior

When you click on the [Edit this page](https://github.com/onflow/cadence-lang.org/docs/measuring-time.mdx) link on any section it takes you to an empty url.

### Expected Behavior

URLs should include [`/blob/main`](https://github.com/onflow/cadence-lang.org/blob/main/docs/measuring-time.mdx)

### Steps To Reproduce

Click the link

### Environment

```markdown
Doesn't matter
```

**Comment by turbolent** [comment]
This was probably already fixed at some point. Confirmed that going to e.g. https://cadence-lang.org/docs/measuring-time and hitting edit leads to the correct GitHub page
