### ISSUE TITLE
[BUG] clicking all search results does not honor version

### ISSUE THREAD

**Issue by bjartek** [onflow/cadence-lang.org#38]
### Current Behavior

- select 1.0 as version in docs
- search for "exists"
- click all results (the fact that i have to scroll down to find this link is not good)
- the search results shown are for 0.42 not 1.0
- 

### Expected Behavior

- the search results shown are for 1.0

### Steps To Reproduce

- select 1.0 as version in docs
- search for "exists"
- click all results (the fact that i have to scroll down to find this link is not good)
- the search results shown are for 0.42 not 1.0
- 

### Environment

```markdown
this is not relevant for this bugreport
```

### What are you currently working on that this is blocking?

Stable cadence

**Comment by turbolent** [comment]
Now that 1.0 is the default, and v0.42 is an older, outdated version, this should be resolved
