### ISSUE TITLE
[FEATURE] Guide for Solidity Developers

### ISSUE THREAD

**Issue by narangchirag** [onflow/cadence-lang.org#8]
### Issue to be solved

1. Website should have a top nav "Guide for Solidity Developers" linking to this item  https://developers.flow.com/cadence/solidity-to-cadence

2. Documentation should link to this blog post https://flow.com/post/implementing-the-bored-ape-yacht-club-smart-

**Comment by gregsantos** [comment]
Full url:

https://flow.com/post/implementing-the-bored-ape-yacht-club-smart-contract-in-cadence

**Comment by turbolent** [comment]
> 1. Website should have a top nav "Guide for Solidity Developers" 

At what position should it appear? All other entries are single words, this one is long and fills up the whole space, e.g. 
![Screenshot 2023-09-12 at 07-16-13 Cadence](https://github.com/onflow/cadence-lang.org/assets/51661/5b0ea7d9-34cc-4811-a92e-c33fa3a887eb)

Can it just be linked to from the existing "Learn" page?

> 2. Documentation should link to this blog post

The "Learn" page already does. For feedback on the documentation, please open an issue in the repo https://github.com/onflow/docs

**Comment by narangchirag** [comment]
I strongly believe Guide for Solidity Devs should be a top nav item after Learn and it can be shortened to "Solidity Guide"
opened a new documentation issue - https://github.com/onflow/docs/issues/272

**Comment by j1010001** [comment]
@gregsantos can you please find someone to takcle the second point ? I tried but I have not figured out how to add a simple link to the docusaurus-autogenerated sidebar.

**Comment by gregsantos** [comment]
Will do Jan

**Comment by jribbink** [comment]
@j1010001 Adding external links to the autogenerated sidebar is sadly a limitation of Docusaurus https://github.com/facebook/docusaurus/discussions/6836.  The only real way around is to write a [custom generator](https://docusaurus.io/docs/next/sidebar/autogenerated#customize-the-sidebar-items-generator) or to manually define the who sidebar.

I could look if there's a clever way to make this work with a custom generator though.  This is something I already ran into and would have appreciated being able to do.

**Comment by gregsantos** [comment]
My understanding is that that blog post should just be linked to from the Guide for Solidity Developers page itself as a reference, not as a sidebar item on dev portal

**Comment by turbolent** [comment]
Done
